unit uScriptUnidades;

interface

const
   UpdatePadraoParaNaoFicarInstrucaoEmBranco = 'update CONFIGURACOES_GERAIS SET ID = ID WHERE ID = ''BD_VERSION''';
                                 //475
   ScriptsBdUnidades: array[228..484] of String = (
     'ALTER  TABLE UNIDADES ALTER {IF FB}DBDIR TYPE VARCHAR(255) CHARACTER SET WIN1252{FI} {IF MSSQL}COLUMN DBDIR VARCHAR(255){FI}',
     'ALTER  TABLE UNIDADES ADD ID_UNID_CLI VARCHAR(32);',
     'ALTER  TABLE UNIDADES ADD IDGRUPO INTEGER;',
     'CREATE TABLE MIDIAS (IDMIDIA INTEGER NOT NULL, NOME VARCHAR(50), ARQUIVO VARCHAR(100), EXTENSAO VARCHAR(10), DURACAOSEGS INTEGER, TIPO CHAR(1), HASH_ARQUIVO VARCHAR(100) NOT NULL);',
     'ALTER  TABLE MIDIAS ADD CONSTRAINT PK_MIDIAS PRIMARY KEY (IDMIDIA);',
     'CREATE TABLE ARQUIVOS (IDMIDIA INTEGER NOT NULL, ARQUIVO_MIDIA {IF FB}BLOB SUB_TYPE 0 SEGMENT SIZE 80{FI} {IF MSSQL}VARBINARY(MAX){FI});',
     'ALTER  TABLE ARQUIVOS ADD CONSTRAINT PK_ARQUIVOS PRIMARY KEY (IDMIDIA);',
     'ALTER  TABLE ARQUIVOS ADD CONSTRAINT FK_ARQUIVOS_MIDIAS FOREIGN KEY (IDMIDIA) REFERENCES MIDIAS (IDMIDIA) ON DELETE CASCADE;',
     'CREATE TABLE GRUPOS (IDGRUPO INTEGER NOT NULL, NOME VARCHAR(50));',
     'ALTER  TABLE GRUPOS ADD CONSTRAINT PK_GRUPOS PRIMARY KEY (IDGRUPO);',
     'ALTER  TABLE UNIDADES ADD CONSTRAINT FK_UNIDADES_GRUPOS FOREIGN KEY (IDGRUPO) REFERENCES GRUPOS (IDGRUPO) ON DELETE CASCADE;',
     'CREATE TABLE GRUPOS_TVS_PLAYLISTS (IDGRUPOTVSPLAYLISTS INTEGER NOT NULL, NOME VARCHAR(50));',
     'ALTER  TABLE GRUPOS_TVS_PLAYLISTS ADD CONSTRAINT PK_GRUPOS_TVS_PLAYLISTS PRIMARY KEY (IDGRUPOTVSPLAYLISTS);',
     'CREATE TABLE GRUPOS_UNIDADES (ID INTEGER NOT NULL, NOME VARCHAR(50), DBDIR VARCHAR(255), IPSERVIDOR VARCHAR(15), PORTA_PA_MPA INTEGER, PORTA_ONL_TGS INTEGER, ID_UNID_CLI VARCHAR(32), IDGRUPO INTEGER NOT NULL);',
     'ALTER  TABLE GRUPOS_UNIDADES ADD CONSTRAINT PK_GRUPOS_UNIDADES PRIMARY KEY (ID);',
     'ALTER  TABLE GRUPOS_UNIDADES ADD CONSTRAINT FK_GRUPOS_UNIDADES_1 FOREIGN KEY (IDGRUPO) REFERENCES GRUPOS (IDGRUPO);',
     'CREATE TABLE LOGS (IDLOG INTEGER NOT NULL, DATAHORA TIMESTAMP NOT NULL, DESCRICAO VARCHAR(100), IDUSUARIO INTEGER, TABELA VARCHAR(30), OPERACAO CHAR(1), COMPLEMENTO {IF FB}BLOB SUB_TYPE 1 SEGMENT SIZE 256{FI} {IF MSSQL}VARCHAR(MAX){FI});',
     'ALTER  TABLE LOGS ADD CONSTRAINT PK_LOGS PRIMARY KEY (IDLOG);',
     'CREATE TABLE PLAYLIST_GRUPO (IDGRUPO INTEGER NOT NULL, ORDEM INTEGER NOT NULL, IDMIDIA INTEGER NOT NULL, DURACAOSEGS INTEGER NOT NULL);',
     'ALTER  TABLE PLAYLIST_GRUPO ADD CONSTRAINT PK_PLAYLIST_GRUPO PRIMARY KEY (IDGRUPO, ORDEM);',
     'ALTER  TABLE PLAYLIST_GRUPO ADD CONSTRAINT FK_PLAYLIST_GRUPOS FOREIGN KEY (IDGRUPO) REFERENCES GRUPOS (IDGRUPO);',
     'ALTER  TABLE PLAYLIST_GRUPO ADD CONSTRAINT FK_PLAYLIST_MIDIAS FOREIGN KEY (IDMIDIA) REFERENCES MIDIAS (IDMIDIA);',
     'CREATE TABLE TVS (IDTV INTEGER NOT NULL, NOME VARCHAR(50), IDUNIDADE INTEGER NOT NULL, IPTV VARCHAR(15), PORTATV INTEGER, ULTIMAATUALIZACAO {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI}, IDGRUPOTVSPLAYLISTS INTEGER);',
     //250

     'ALTER  TABLE TVS ADD CONSTRAINT PK_TVS PRIMARY KEY (IDTV);',
     'ALTER  TABLE TVS ADD CONSTRAINT FK_TVS_1 FOREIGN KEY (IDGRUPOTVSPLAYLISTS) REFERENCES GRUPOS_TVS_PLAYLISTS (IDGRUPOTVSPLAYLISTS);',
     'ALTER  TABLE TVS ADD CONSTRAINT FK_TVS_UNIDADES FOREIGN KEY (IDUNIDADE) REFERENCES UNIDADES (ID);',
     'CREATE TABLE PLAYLIST_LOGS (ID INTEGER NOT NULL, IDTV INTEGER NOT NULL, IP VARCHAR(15) NOT NULL, DATAHORA {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI} NOT NULL);',
     'ALTER  TABLE PLAYLIST_LOGS ADD CONSTRAINT PK_PLAYLIST_LOGS PRIMARY KEY (ID);',
     'ALTER  TABLE PLAYLIST_LOGS ADD CONSTRAINT FK_PLAYLIST_LOGS_1 FOREIGN KEY (IDTV) REFERENCES TVS (IDTV);',
     'CREATE TABLE USUARIOS (IDUSUARIO  INTEGER NOT NULL, NOME VARCHAR(50), LOGIN VARCHAR(50), SENHA VARCHAR(50), ATIVO CHAR(1));',
     'ALTER  TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIO);',
     '{IF FB}CREATE SEQUENCE GEN_ARQUIVOS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     '{IF FB}CREATE SEQUENCE GEN_GRUPOS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     '{IF FB}CREATE SEQUENCE GEN_LOGS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     '{IF FB}CREATE SEQUENCE GEN_MIDIAS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     '{IF FB}CREATE SEQUENCE GEN_PLAYLIST_LOGS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     '{IF FB}CREATE SEQUENCE GEN_TVS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     '{IF FB}CREATE SEQUENCE GEN_USUARIOS_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     'CREATE TABLE INDICADORES (ID BIGINT NOT NULL, ID_UNIDADE INT, NOME_UNIDADE VARCHAR(50), PINOME VARCHAR(40), VALOR VARCHAR(20), ID_PINIVEL INT, CODIGOCOR INT, NOMENIVEL VARCHAR(20), POSICAONIVEL INT, VALOR_NUMERICO INT, FLAG_VALOR_EM_SEGUNDOS CHAR(1));',
     'ALTER  TABLE INDICADORES ADD CREATEDAT {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI};',
     'ALTER  TABLE INDICADORES ADD CONSTRAINT PK_INDICADORES PRIMARY KEY (ID);',
     '{IF FB}CREATE SEQUENCE GEN_INDICADORES_ID;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
     'ALTER  TABLE UNIDADES ADD HOST VARCHAR(100);',
     'ALTER  TABLE UNIDADES ADD BANCO VARCHAR(100);',
     'ALTER  TABLE UNIDADES ADD USUARIO VARCHAR(100);',
     'ALTER  TABLE UNIDADES ADD SENHA VARCHAR(255);',
     'ALTER  TABLE UNIDADES ADD OSAUTHENT CHAR(1);',
     'CREATE TABLE GENERATORS(NOME  VARCHAR(40) NOT NULL, VALOR INTEGER);',
     'ALTER TABLE GENERATORS ADD CONSTRAINT PK_GENERATOR PRIMARY KEY (NOME);',
     'CREATE TABLE DEVICES(ID VARCHAR(36) NOT NULL, NOME VARCHAR(50) NOT NULL, STATUS CHAR(1), ULTIMO_ACESSO {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI});',
     'ALTER TABLE DEVICES ADD CONSTRAINT PK_DEVICES PRIMARY KEY (ID);',
     'CREATE TABLE DEVICES_UNIDADES(ID_DEVICE VARCHAR(36) NOT NULL, ID_UNIDADE INTEGER NOT NULL);',
     'ALTER TABLE DEVICES_UNIDADES ADD CONSTRAINT PK_DEVICES_UNIDADES PRIMARY KEY (ID_DEVICE,ID_UNIDADE);',
     'ALTER TABLE DEVICES_UNIDADES ADD CONSTRAINT FK_DEVICES_UNIDADES_1 FOREIGN KEY (ID_DEVICE) REFERENCES DEVICES(ID);',
     'ALTER TABLE DEVICES_UNIDADES ADD CONSTRAINT FK_DEVICES_UNIDADES_2 FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID);',
     'ALTER TABLE INDICADORES DROP {IF MSSQL}COLUMN{FI} NOME_UNIDADE;',
     'INSERT INTO GENERATORS VALUES(0,''GEN_ARQUIVOS_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_GRUPOS_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_INDICADORES_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_LOGS_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_MIDIAS_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_PLAYLIST_LOGS_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_TVS_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_UNIDADES_ID'', 0)',
     'INSERT INTO GENERATORS VALUES(0,''GEN_USUARIOS_ID'', 0)',
     'ALTER TABLE UNIDADES ADD TIPOBANCO CHAR(1)',
     'ALTER TABLE UNIDADES ALTER {IF FB}IP TYPE VARCHAR(255) CHARACTER SET WIN1252{FI} {IF MSSQL}COLUMN IP VARCHAR(255){FI}',

     'CREATE TABLE DISPOSITIVOS_STATUS (ID INTEGER NOT NULL, ID_UNIDADE INTEGER NOT NULL,'
        + 'ID_UNID_CLI INTEGER, NOME_UNIDADE VARCHAR(100), STATUS_UNIDADE VARCHAR(50), TIPO_DISPOSITIVO VARCHAR(50),'
        + 'NOME_DISPOSITIVO VARCHAR(100), MODELO_DISPOSITIVO VARCHAR(50), IP VARCHAR(15),STATUS VARCHAR(50), ULTIMAATUALIZACAO TIMESTAMP);',
     'CREATE SEQUENCE GEN_DISPOSITIVOS_STATUS_ID;',
     'CREATE TABLE DISPOSITIVOS_STATUS_ONLINE ('
        + ' ID                  INTEGER NOT NULL,'
        + ' ID_UNIDADE          INTEGER,'
        + ' TIPO_DISPOSITIVO    VARCHAR(50),'
        + ' NOME_DISPOSITIVO    VARCHAR(100),'
        + ' MODELO_DISPOSITIVO  VARCHAR(50),'
        + ' DATAHORA            TIMESTAMP)',
     'ALTER TABLE DISPOSITIVOS_STATUS_ONLINE ADD CONSTRAINT PK_DISPOSITIVOS_STATUS_ONLINE PRIMARY KEY (ID)',
     'CREATE INDEX IDX_IDENTIFICADOR_DEVICE ON DISPOSITIVOS_STATUS_ONLINE (ID_UNIDADE, TIPO_DISPOSITIVO, NOME_DISPOSITIVO, MODELO_DISPOSITIVO)',
     'CREATE TABLE MONITOR_TOTEM(ID INT NOT NULL, ID_UNIDADE INT NOT NULL, TOTEM VARCHAR(50) NOT NULL, TOTAL INT NOT NULL, SUCESSO INT NOT NULL, ERRO INT NOT NULL, R_DATA DATE NOT NULL)',
     //300

     'ALTER TABLE MONITOR_TOTEM ADD CONSTRAINT PK_MONITOR_TOTEM_ID PRIMARY KEY (ID);',
     'DROP TABLE MONITOR_TOTEM;',
     'CREATE TABLE MONITOR_TOTEM(ID INTEGER NOT NULL, ID_UNIDADE INTEGER NOT NULL, TOTEM VARCHAR(50) NOT NULL, DESCRICAO VARCHAR(50), VALOR VARCHAR(50), R_DATA DATE);',
     'ALTER TABLE MONITOR_TOTEM ADD CONSTRAINT PK_MONITOR_TOTEM_ID PRIMARY KEY (ID);',
     '{IF FB}CREATE TABLE GRUPOS_FILAS (ID INTEGER NOT NULL,NOME NOME_NORMAL);{FI}{IF MSSQL}CREATE TABLE GRUPOS_FILAS (ID INTEGER NOT NULL,NOME VARCHAR(30));{FI}',
     '{IF FB}ALTER TABLE GRUPOS_FILAS ADD CONSTRAINT PK_GRUPOS_FILAS PRIMARY KEY (ID);{FI}{IF MSSQL}ALTER TABLE GRUPOS_FILAS ADD CONSTRAINT PK_GRUPOS_FILAS PRIMARY KEY (ID);{FI}',
     '{IF FB}CREATE TABLE CATEGORIAS_FILAS (ID INTEGER NOT NULL,NOME NOME_NORMAL);{FI}{IF MSSQL}CREATE TABLE CATEGORIAS_FILAS (ID INTEGER NOT NULL,NOME VARCHAR(30));{FI}',
     '{IF FB}ALTER TABLE CATEGORIAS_FILAS ADD CONSTRAINT PK_CATEGORIAS_FILAS PRIMARY KEY (ID);{FI}{IF MSSQL}ALTER TABLE CATEGORIAS_FILAS ADD CONSTRAINT PK_CATEGORIAS_FILAS PRIMARY KEY (ID);{FI}',
     'ALTER TABLE FILAS ADD ID_GRUPOFILA INTEGER;',
     'ALTER TABLE FILAS ADD CONSTRAINT FK_FILAS_1 FOREIGN KEY (ID_GRUPOFILA) REFERENCES GRUPOS_FILAS(ID);',
     'ALTER TABLE FILAS ADD ID_CATEGORIAFILA INTEGER;',
     'ALTER TABLE FILAS ADD CONSTRAINT FK_FILAS_2 FOREIGN KEY (ID_CATEGORIAFILA) REFERENCES CATEGORIAS_FILAS(ID);',

     '{IF FB}CREATE TABLE CALCULOS_TEE (ID INTEGER NOT NULL, ID_UNIDADE INTEGER NOT NULL, ID_FILA INTEGER, DATAHORA TIMESTAMP, PARAMETROS_CALCULO VARCHAR(1000), RESULTADO TIMESTAMP);{FI}'
        + '{IF MSSQL}CREATE TABLE CALCULOS_TEE (ID INTEGER NOT NULL, ID_UNIDADE INTEGER NOT NULL, ID_FILA INTEGER, DATAHORA DATETIME, PARAMETROS_CALCULO VARCHAR(1000), RESULTADO DATETIME);{FI}',
     '{IF FB}ALTER TABLE CALCULOS_TEE ADD CONSTRAINT PK_CALCULOSTEE PRIMARY KEY (ID);{FI}{IF MSSQL}ALTER TABLE CALCULOS_TEE ADD CONSTRAINT PK_CALCULOSTEE PRIMARY KEY (ID);{FI}',
     'ALTER TABLE CALCULOS_TEE ADD CONSTRAINT FK_CALCULOSTEE_UNIDADES FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID);',
     'INSERT INTO GENERATORS VALUES(0,''GEN_ID_PARAMETROSCALCULOTEE'', 0)',
     'ALTER TABLE ATENDENTES ADD ID_ATD_CLI INTEGER',
      'CREATE TABLE SMARTSURV_EMPRESAS (ID INTEGER NOT NULL, NOME VARCHAR(50) NOT NULL, IMG_FUNDO VARCHAR(80), ' +
          'IMG_OBRIGADO VARCHAR(80), IMG_LOGOEMPRESA VARCHAR(80), ATIVA CHAR(1) DEFAULT ''N'', PERG_TAMANHO_FONTE INTEGER, ' +
          'PERG_COR_FONTE INTEGER, PERG_TOP INTEGER, PERG_LEFT INTEGER, PERG_WIDTH INTEGER, PERG_HEIGHT INTEGER, SEGS_OBRIGADO INTEGER, ' +
          'LOGIN INTEGER, SENHA VARCHAR(30));',
      'ALTER TABLE SMARTSURV_EMPRESAS ADD CONSTRAINT PK_SS_EMPRESA PRIMARY KEY (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_EMPRESAS;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_EMPRESAS'', 0);',
      'CREATE TABLE SMARTSURV_BOTOES (ID INTEGER NOT NULL, DESCRICAO VARCHAR(40), IMG_NORMAL VARCHAR(80), IMG_PRESSIONADO VARCHAR(80));',
      'ALTER TABLE SMARTSURV_BOTOES ADD CONSTRAINT PK_SS_BOTOES PRIMARY KEY (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_BOTOES;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_BOTOES'', 0);',
      'CREATE TABLE SMARTSURV_PERGUNTAS (ID INTEGER NOT NULL, EMPRESA_ID INTEGER, TEXTO VARCHAR(400), IMG_FUNDO VARCHAR(80), ' +
          'TEMPLATE CHAR(1) DEFAULT ''N'', PERG_TAMANHO_FONTE INTEGER, PERG_COR_FONTE INTEGER, PERG_TOP INTEGER, PERG_LEFT INTEGER, ' +
          'PERG_WIDTH INTEGER, PERG_HEIGHT INTEGER);',
      'ALTER TABLE SMARTSURV_PERGUNTAS ADD CONSTRAINT PK_SS_PERGUNTA PRIMARY KEY (ID);',
      'ALTER TABLE SMARTSURV_PERGUNTAS ADD CONSTRAINT FK_SS_PERGUNTA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES SMARTSURV_EMPRESAS (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_PERGUNTAS;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_PERGUNTAS'', 0);',
      'CREATE TABLE SMARTSURV_ALTERNATIVAS (ID INTEGER NOT NULL, PERGUNTA_ID INTEGER, LABEL VARCHAR(200), ORDEM INTEGER, ' +
          'COR INTEGER, BTN_TOP INTEGER, BTN_LEFT INTEGER, BTN_WIDTH INTEGER, BTN_HEIGHT INTEGER, BOTAO_ID INTEGER, ' +
          'TIPO SMALLINT DEFAULT 0, CAMPO VARCHAR(20));',
      'ALTER TABLE SMARTSURV_ALTERNATIVAS ADD CONSTRAINT PK_SS_ALTERNATIVA PRIMARY KEY (ID);',
      'ALTER TABLE SMARTSURV_ALTERNATIVAS ADD CONSTRAINT FK_SSALTERNATIVA_BOTOES FOREIGN KEY (BOTAO_ID) REFERENCES SMARTSURV_BOTOES (ID);',
      'ALTER TABLE SMARTSURV_ALTERNATIVAS ADD CONSTRAINT FK_SSALTERNATIVA_PERGUNTA FOREIGN KEY (PERGUNTA_ID) REFERENCES SMARTSURV_PERGUNTAS (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_ALTERNATIVAS;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_ALTERNATIVAS'', 0);',
      'CREATE TABLE SMARTSURV_NN_EMPRESAS_PERGUNTAS ( EMPRESA_ID INTEGER NOT NULL, PERGUNTA_ID INTEGER NOT NULL, POSICAO INTEGER);',
      'ALTER TABLE SMARTSURV_NN_EMPRESAS_PERGUNTAS ADD CONSTRAINT PK_SS_EMPRESAS_PERGUNTAS PRIMARY KEY (EMPRESA_ID, PERGUNTA_ID);',
      'ALTER TABLE SMARTSURV_NN_EMPRESAS_PERGUNTAS ADD CONSTRAINT FK_SS_PERGUNTAS_EMPRESAS FOREIGN KEY (EMPRESA_ID) REFERENCES SMARTSURV_EMPRESAS (ID);',
      'ALTER TABLE SMARTSURV_NN_EMPRESAS_PERGUNTAS ADD CONSTRAINT FK_SS_PERGUNTAS_PERGUNTAS FOREIGN KEY (PERGUNTA_ID) REFERENCES SMARTSURV_PERGUNTAS (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_NN_EMPS_PERGS;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_NN_EMPS_PERGS'', 0);',
      'CREATE TABLE SMARTSURV_RESPOSTAS ( ID INTEGER NOT NULL, ALTERNATIVA_ID INTEGER, DEVICE_ID INTEGER, DATAHORA TIMESTAMP, GUID VARCHAR(38), TICKET INTEGER);',
      'ALTER TABLE SMARTSURV_RESPOSTAS ADD CONSTRAINT PK_SS_RESPOSTA PRIMARY KEY (ID);',
      'ALTER TABLE SMARTSURV_RESPOSTAS ADD CONSTRAINT FK_SS_RESPOSTA_ALTERNATIVA FOREIGN KEY (ALTERNATIVA_ID) REFERENCES SMARTSURV_ALTERNATIVAS (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_RESPOSTAS;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_RESPOSTAS'', 0);',
      'CREATE TABLE SMARTSURV_RESPOSTAS_DET (ID INTEGER NOT NULL, RESPOSTA_ID INTEGER, CAMPO VARCHAR(20), VALOR {IF FB}BLOB SUB_TYPE 1 SEGMENT SIZE 80{FI} {IF MSSQL}VARBINARY(MAX){FI});',
      'ALTER TABLE SMARTSURV_RESPOSTAS_DET ADD CONSTRAINT PK_SS_RESPOSTAS_DET PRIMARY KEY (ID);',
      'ALTER TABLE SMARTSURV_RESPOSTAS_DET ADD CONSTRAINT FK_SS_RESPOSTAS_RESPOSTAS_DET FOREIGN KEY (RESPOSTA_ID) REFERENCES SMARTSURV_RESPOSTAS (ID);',
      '{IF FB}CREATE SEQUENCE GEN_ID_SMARTSURV_RESPOSTAS_DET;{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'INSERT INTO GENERATORS VALUES(0,''GEN_ID_SMARTSURV_RESPOSTAS_DET'', 0);',
      'ALTER TABLE ATENDENTES ADD ID_TRIAGEM INT;',
      'ALTER TABLE MODULOS_MULTIPAS ADD MOSTRAR_BOTAO_SEGUIRATENDIMENTO {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      'ALTER TABLE MODULOS_MULTIPAS ADD MOSTRAR_MENU_SEGUIRATENDIMENTO {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      'ALTER TABLE MODULOS_MULTIPAS ADD CODIGOS_UNIDADES VARCHAR(50);',
      'ALTER TABLE MODULOS_MULTIPAS ADD ID_UNIDADE_CLI INTEGER;',
      'ALTER TABLE MODULOS_MULTIPAS ADD FILA_ESPERA_PROFISSIONAL INTEGER;',
      'ALTER TABLE MODULOS_PAS ADD MOSTRAR_BOTAO_SEGUIRATENDIMENTO {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      'ALTER TABLE MODULOS_PAS ADD MOSTRAR_MENU_SEGUIRATENDIMENTO {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      'ALTER TABLE MODULOS_PAS ADD CODIGOS_UNIDADES VARCHAR(50);',
      'ALTER TABLE MODULOS_PAS ADD ID_UNIDADE_CLI INTEGER;',
      'ALTER TABLE MODULOS_PAS ADD FILA_ESPERA_PROFISSIONAL INTEGER;',
      'ALTER TABLE MODULOS_ONLINE ADD ID_UNIDADE_CLI INTEGER ;',
      'ALTER TABLE PAS ADD WHATSAPP {IF FB} BOOLEAN {FI}{IF MSSQL}VARCHAR(1){FI};',
      'ALTER TABLE CALCULOS_TEE DROP CONSTRAINT PK_CALCULOSTEE;',
      'ALTER TABLE CALCULOS_TEE ADD CONSTRAINT PK_CALCULOSTEE PRIMARY KEY (ID,ID_UNIDADE);',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_PAS ADD DEFAULT(''F'') FOR MOSTRAR_BOTAO_SEGUIRATENDIMENTO{FI};',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_PAS ADD DEFAULT(''F'') FOR MOSTRAR_MENU_SEGUIRATENDIMENTO{FI};',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_MULTIPAS ADD DEFAULT(''F'') FOR MOSTRAR_BOTAO_SEGUIRATENDIMENTO{FI};',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_MULTIPAS ADD DEFAULT(''F'') FOR MOSTRAR_MENU_SEGUIRATENDIMENTO{FI};',
      'ALTER TABLE MODULOS_MULTIPAS ADD MOSTRAR_PAINEL_GRUPOS {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_MULTIPAS ADD DEFAULT(''F'') FOR MOSTRAR_PAINEL_GRUPOS{FI};',
      'ALTER TABLE MODULOS_PAS ADD MARCAR_TAG_APOS_ATENDIMENTO {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      'ALTER TABLE MODULOS_PAS ADD ID_TAG_AUTOMATICA INTEGER;',
      'ALTER TABLE MODULOS_MULTIPAS ADD MARCAR_TAG_APOS_ATENDIMENTO {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
      'ALTER TABLE MODULOS_MULTIPAS ADD ID_TAG_AUTOMATICA INTEGER;',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_PAS ADD DEFAULT(''F'') FOR MARCAR_TAG_APOS_ATENDIMENTO{FI};',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_MULTIPAS ADD DEFAULT(''F'') FOR MARCAR_TAG_APOS_ATENDIMENTO{FI};',
      //379

      //Manipulações DDL para o Gerenciador de Totens
      '{IF FB}CREATE DOMAIN BOOLEAN AS CHAR(1) DEFAULT ''F'' CHECK (VALUE IN(''T'', ''F''));{FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      'CREATE TABLE GRUPOS_PERMISSOES (ID INTEGER NOT NULL, NOME VARCHAR(50))',
      'ALTER TABLE GRUPOS_PERMISSOES ADD CONSTRAINT PK_GRUPOSPERMISSOES PRIMARY KEY (ID)',

      'CREATE TABLE PERMISSOES (ID INTEGER NOT NULL, NOME VARCHAR(50), ID_GRUPO INTEGER NOT NULL)',
      'ALTER TABLE PERMISSOES ADD CONSTRAINT PK_PERMISSOES PRIMARY KEY (ID)',
      'ALTER TABLE PERMISSOES ADD CONSTRAINT FK_PERMISSOES_GRUPOS FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS_PERMISSOES (ID)',

      'CREATE TABLE GRUPOS_USUARIOS (ID INTEGER NOT NULL, NOME VARCHAR(50))',
      'ALTER TABLE GRUPOS_USUARIOS ADD CONSTRAINT PK_GRUPOSUSUARIOS PRIMARY KEY (ID)',

      //[LBC 14/03/2022] A tabela USUARIOS estava sendo utilizada no módulo TVCorporativa do SICS.
      //                 Porém, creio que até hoje nenhum cliente efetivamente utiliza este módulo.
      //                 Por via das dúvidas, vou colocar os dados em outra tabela e, posteriormente,
      //                 precisaremos revisar o módulo TVCorporativa para usar a tabela USUARIOS conforme
      //                 estrutura sendo criada agora (com a PK em ID ao invés de IDUSUARIO).
      'CREATE TABLE BCKP_TVCORP_USUARIOS (IDUSUARIO  INTEGER NOT NULL, NOME VARCHAR(50), LOGIN VARCHAR(50), SENHA VARCHAR(50), ATIVO CHAR(1))',
      'ALTER  TABLE BCKP_TVCORP_USUARIOS ADD CONSTRAINT PK_BCKPTVCORPUSUARIOS PRIMARY KEY (IDUSUARIO)',
      'INSERT INTO BCKP_TVCORP_USUARIOS SELECT * FROM USUARIOS',
      'DROP TABLE USUARIOS',

      'CREATE TABLE USUARIOS (ID INTEGER NOT NULL, NOME VARCHAR(100), ID_GRUPO INTEGER, LOGIN VARCHAR(50), SENHA VARCHAR(32), ATIVO {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI})',
      'ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID)',
      'ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_GRUPOS FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS_USUARIOS (ID)',

      'CREATE TABLE NN_GRUPOSUSUARIOS_PERMISSOES (ID_GRUPO INTEGER NOT NULL, ID_PERMISSAO INTEGER NOT NULL, PERMITE {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI})',
      'ALTER TABLE NN_GRUPOSUSUARIOS_PERMISSOES ADD CONSTRAINT PK_NNGRUPOSUSUARIOSPERMISSOES PRIMARY KEY (ID_GRUPO, ID_PERMISSAO)',
      'ALTER TABLE NN_GRUPOSUSUARIOS_PERMISSOES ADD CONSTRAINT FK_NNGRUPOSUSUARIOSPERM_GRUPOS FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS_USUARIOS (ID)',
      'ALTER TABLE NN_GRUPOSUSUARIOS_PERMISSOES ADD CONSTRAINT FK_NNGRUPOSUSUARIOSPERM_PERM FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSOES (ID)',

      //[LBC 14/03/2022] A tabela LOGS estava sendo utilizada no módulo TVCorporativa do SICS.
      //                 Porém, creio que até hoje nenhum cliente efetivamente utiliza este módulo.
      //                 Por via das dúvidas, vou colocar os dados em outra tabela e, posteriormente,
      //                 precisaremos revisar o módulo TVCorporativa para usar a tabela LOGS conforme
      //                 estrutura sendo criada agora (uma tabela LOGS e uma tabela para cada tipo de Log).
      //                 Ao revisar o módulo, poderemos usar a unit udmLogs deste projeto.
      'CREATE TABLE BCKP_TVCORP_LOGS (IDLOG INTEGER NOT NULL, DATAHORA {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI} NOT NULL, DESCRICAO VARCHAR(100), ' +
          'IDUSUARIO INTEGER, TABELA VARCHAR(30), OPERACAO CHAR(1), COMPLEMENTO {IF FB}BLOB SUB_TYPE 1 SEGMENT SIZE 256{FI} {IF MSSQL}VARCHAR(MAX){FI});',
      'ALTER  TABLE BCKP_TVCORP_LOGS ADD CONSTRAINT PK_BCKPTVCORPLOGS PRIMARY KEY (IDLOG)',
      'INSERT INTO BCKP_TVCORP_LOGS SELECT * FROM LOGS',
      'DROP TABLE LOGS',
      //402

      'CREATE TABLE GRUPOS_LOGS (ID INTEGER NOT NULL, NOME VARCHAR(40))',
      'ALTER TABLE GRUPOS_LOGS ADD CONSTRAINT PK_GRUPOSLOGS PRIMARY KEY (ID)',

      'CREATE TABLE LOGS (ID INTEGER NOT NULL, ID_GRUPO_LOG INTEGER NOT NULL, ID_USUARIO INTEGER, DATA_HORA {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI} DEFAULT CURRENT_TIMESTAMP)',
      'ALTER TABLE LOGS ADD CONSTRAINT PK_LOGS PRIMARY KEY (ID)',
      'ALTER TABLE LOGS ADD CONSTRAINT FK_LOGS_GRUPOSLOGS FOREIGN KEY (ID_GRUPO_LOG) REFERENCES GRUPOS_LOGS (ID)',
      'CREATE INDEX IDX_LOGS_DATAHORA ON LOGS (DATA_HORA)',

      'CREATE TABLE LOGS_CONFIG_TABELA (ID_LOG INTEGER NOT NULL, TABELA VARCHAR(80), OPERACAO VARCHAR(1), DADOS {IF FB}BLOB SUB_TYPE 1 SEGMENT SIZE 80{FI} {IF MSSQL}VARCHAR(MAX){FI})',
      'ALTER TABLE LOGS_CONFIG_TABELA ADD CONSTRAINT PK_LOGSCONFIGTABELA PRIMARY KEY (ID_LOG)',
      'ALTER TABLE LOGS_CONFIG_TABELA ADD CONSTRAINT FK_LOGSCONFIGTABELA_LOGS FOREIGN KEY (ID_LOG) REFERENCES LOGS (ID)',

      //Na V6 essa tabela é criada no banco de Unidades. Na V7 jé tem essa tabela (que é a tabela de totens de cada unidade mesmo),
      //  porém com o tamanho do campo NOME em varchar(30) e sem o campo ATIVO, então na V7 faremos um ALTER TABLE nestes 2 campos
      '{IF FB}UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_SOURCE = ''NOME_LONGO'' WHERE (RDB$FIELD_NAME = ''NOME'') AND (RDB$RELATION_NAME = ''TOTENS''){FI}' +
        '{IF MSSQL}ALTER TABLE TOTENS ALTER COLUMN NOME VARCHAR(60){FI}',
      'ALTER TABLE TOTENS ADD ATIVO {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI}',

      //Para funcionar o gerenciador de totens e o totem AA, a PK correta para esta tabela deve ser o ID mesmo, e não a chave composta ID_UNIDADE,ID,
      //  de modo que o ID do totem seja sequencial para todas as Unidades e não por Unidade.
      //  Porém, esta alteração necessita de uma alteração grande no SicsServidor (alterando toda a estutura de vlTotens e IdsTotens, por exemplo).
      //  Desta forma, ficará comentado neste momento e POSTERIORMENTE DEVERÁ ser alterada esta PK, junto com a versão de servidor:
      //  'ALTER TABLE TOTENS DROP CONSTRAINT PK_TOTENS',
      //  'ALTER TABLE TOTENS ADD CONSTRAINT PK_TOTENS PRIMARY KEY (ID)',
      //  OBS: Terá que ser feito o upgrade de TODOS os servidores antes de dropar e alterar a PK. Este processo, em clientes com muitas Unidades como o Fleury, levará muitos dias.

      'CREATE TABLE PARAMTOTENS_GRUPOSCHAVES (ID INTEGER NOT NULL, NOME VARCHAR(100) NOT NULL, DESCRICAO VARCHAR(2000) NOT NULL)',
      'ALTER TABLE PARAMTOTENS_GRUPOSCHAVES ADD CONSTRAINT PK_PARAMTOTENS_GRUPOSCHAVES PRIMARY KEY (ID)',

      'CREATE TABLE PARAMTOTENS_CHAVES (ID INTEGER NOT NULL, ID_GRUPO INTEGER NOT NULL, NOME VARCHAR(100) NOT NULL, DESCRICAO VARCHAR(2000) NOT NULL)',
      'ALTER TABLE PARAMTOTENS_CHAVES ADD CONSTRAINT PK_PARAMTOTENS_CHAVES PRIMARY KEY (ID)',
      'ALTER TABLE PARAMTOTENS_CHAVES ADD CONSTRAINT FK_PARAMTOTENS_CHAVES_GRUPOS FOREIGN KEY (ID_GRUPO) REFERENCES PARAMTOTENS_GRUPOSCHAVES (ID)',

      'CREATE TABLE NN_PARAMTOTENS_CHAVES_TOTENS (ID_TOTEM INTEGER NOT NULL, ID_CHAVE INTEGER NOT NULL, VALOR VARCHAR(1000), ALTERADO_POR INTEGER, ALTERADO_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI})',
      'ALTER TABLE NN_PARAMTOTENS_CHAVES_TOTENS ADD CONSTRAINT PK_NN_PARAMTOTENS_CHAVES_TOTENS PRIMARY KEY (ID_TOTEM,ID_CHAVE)',
      'ALTER TABLE NN_PARAMTOTENS_CHAVES_TOTENS ADD CONSTRAINT FK_NNPARAMTOTCHAVESTOTENS_CHAVE FOREIGN KEY (ID_CHAVE) REFERENCES PARAMTOTENS_CHAVES(ID)',
      'ALTER TABLE NN_PARAMTOTENS_CHAVES_TOTENS ADD CONSTRAINT FK_NNPARAMTOTCHAVESTOTENS_USUAR FOREIGN KEY (ALTERADO_POR) REFERENCES USUARIOS(ID)',

      //Para funcionar corretamente o gerenciador de totens e o totem AA, deve-se criar esta FK abaixo nesta tabela.
      //  Porém, esta alteração necessita que o campo ID seja PK na tabela TOTENS, ou seja depende da alteração grande no SicsServidor
      //  descrita acima. Desta forma, ficará comentado neste momento e POSTERIORMENTE DEVERÁ ser criada esta PK, junto com a versão do servidor:
      //  'ALTER TABLE NN_PARAMTOTENS_CHAVES_TOTENS ADD CONSTRAINT FK_NNPARAMTOTCHAVESTOTENS_TOTEM FOREIGN KEY (ID_TOTEM) REFERENCES TOTENS(ID)',

      'CREATE TABLE LOGS_PARAMETRIZACAO_TOTEM (ID_LOG INTEGER NOT NULL, TIPO_EDICAO VARCHAR(30), ID_TOTEM INTEGER, ID_CHAVE INTEGER, VALOR_ANTERIOR VARCHAR(1000), VALOR_NOVO VARCHAR(1000))',
      'ALTER TABLE LOGS_PARAMETRIZACAO_TOTEM ADD CONSTRAINT PK_LOGS_PARAMETRIZACAO_TOTEM PRIMARY KEY (ID_LOG)',
      'ALTER TABLE LOGS_PARAMETRIZACAO_TOTEM ADD CONSTRAINT FK_LOGSPARAMTOTEM_IDCHAVE FOREIGN KEY (ID_CHAVE) REFERENCES PARAMTOTENS_CHAVES(ID)',

      //Para funcionar corretamente o gerenciador de totens e o totem AA, deve-se criar esta FK abaixo nesta tabela.
      //  Porém, esta alteração necessita que o campo ID seja PK na tabela TOTENS, ou seja depende da alteração grande no SicsServidor
      //  descrita acima. Desta forma, ficará comentado neste momento e POSTERIORMENTE DEVERÁ ser criada esta PK, junto com a versão do servidor:
      //  'ALTER TABLE LOGS_PARAMETRIZACAO_TOTEM ADD CONSTRAINT FK_LOGSPARAMTOTEM_IDTOTEM FOREIGN KEY (ID_TOTEM) REFERENCES TOTENS(ID)',

      'CREATE TABLE TIPOS_EXECUTAVEIS (ID INTEGER NOT NULL, NOME VARCHAR(40))',
      'ALTER TABLE TIPOS_EXECUTAVEIS ADD CONSTRAINT PK_TIPOSEXECUTAVEIS PRIMARY KEY (ID)',

      'CREATE TABLE EXECUTAVEIS (ID INTEGER NOT NULL, ID_TIPO INTEGER, ORIGINAL_FILENAME VARCHAR(50), ORIGINAL_FILESIZE INTEGER, VERSAO VARCHAR(50), BINARIO {IF FB}BLOB SUB_TYPE 0 SEGMENT SIZE 80{FI} {IF MSSQL}VARBINARY(MAX){FI}, BINARIO_HASH VARCHAR(32),' +
        'UPLOADED_POR INTEGER, UPLOADED_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI}, ULTIMOUSO_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI}, DELETADO {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI})',
      'ALTER TABLE EXECUTAVEIS ADD CONSTRAINT PK_EXECUTAVEIS PRIMARY KEY (ID)',
      'ALTER TABLE EXECUTAVEIS ADD CONSTRAINT FK_EXECUTAVEIS_TIPOS FOREIGN KEY (ID_TIPO) REFERENCES TIPOS_EXECUTAVEIS(ID)',

      'CREATE TABLE TIPOS_STATUS_DEPLOY (ID INTEGER NOT NULL, NOME VARCHAR(100))',
      'ALTER TABLE TIPOS_STATUS_DEPLOY ADD CONSTRAINT PK_TIPOSSTATUSDEPLOY PRIMARY KEY (ID)',
      //432

      'CREATE TABLE TOTENS_VERSOES (ID_TOTEM INTEGER NOT NULL, ID_TIPOEXECUTAVEL INTEGER NOT NULL,' +
        'VERSAO_ANTERIOR_ID INTEGER, VERSAO_ANTERIOR_DEPLOYED_POR INTEGER, VERSAO_ANTERIOR_DEPLOYED_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI},' +
        'VERSAO_ATUAL_ID INTEGER, VERSAO_ATUAL_DEPLOYED_POR INTEGER, VERSAO_ATUAL_DEPLOYED_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI},' +
        'VERSAO_PROXIMA_ID INTEGER, VERSAO_PROXIMA_DEPLOYED_POR INTEGER, VERSAO_PROXIMA_DEPLOYED_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI},' +
        'ID_STATUS_DEPLOY INTEGER)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT PK_TOTENS_VERSOES PRIMARY KEY (ID_TOTEM,ID_TIPOEXECUTAVEL)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_VERANT_ID FOREIGN KEY (VERSAO_ANTERIOR_ID) REFERENCES EXECUTAVEIS(ID)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_VERANT_DEPLOYEDPOR FOREIGN KEY (VERSAO_ANTERIOR_DEPLOYED_POR) REFERENCES USUARIOS(ID)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_VERATU_ID FOREIGN KEY (VERSAO_ATUAL_ID) REFERENCES EXECUTAVEIS(ID)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_VERATU_DEPLOYEDPOR FOREIGN KEY (VERSAO_ATUAL_DEPLOYED_POR) REFERENCES USUARIOS(ID)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_VERPROX_ID FOREIGN KEY (VERSAO_PROXIMA_ID) REFERENCES EXECUTAVEIS(ID)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_VERPROX_DEPLOYEDPOR FOREIGN KEY (VERSAO_PROXIMA_DEPLOYED_POR) REFERENCES USUARIOS(ID)',
      'ALTER TABLE TOTENS_VERSOES ADD CONSTRAINT FK_TOTENS_STATUSDEPLOY FOREIGN KEY (ID_STATUS_DEPLOY) REFERENCES TIPOS_STATUS_DEPLOY(ID)',

      'CREATE TABLE LOGS_DEPLOY_VERSOES (ID_LOG INTEGER NOT NULL, ID_TOTEM INTEGER, ID_TIPO_EXECUTAVEL INTEGER, ID_VERSAO_ATUAL INTEGER, ID_VERSAO_NOVA INTEGER, ID_STATUS_DEPLOY INTEGER)',
      'ALTER TABLE LOGS_DEPLOY_VERSOES ADD CONSTRAINT PK_LOGS_DEPLOY_VERSOES PRIMARY KEY (ID_LOG)',
      'ALTER TABLE LOGS_DEPLOY_VERSOES ADD CONSTRAINT FK_LOGSDEPLOYVERSOES_TIPOEXEC FOREIGN KEY (ID_TIPO_EXECUTAVEL) REFERENCES TIPOS_EXECUTAVEIS(ID)',
      'ALTER TABLE LOGS_DEPLOY_VERSOES ADD CONSTRAINT FK_LOGSDEPLOYVERSOES_VERATUAL FOREIGN KEY (ID_VERSAO_ATUAL) REFERENCES EXECUTAVEIS(ID)',
      'ALTER TABLE LOGS_DEPLOY_VERSOES ADD CONSTRAINT FK_LOGSDEPLOYVERSOES_VERNOVA FOREIGN KEY (ID_VERSAO_NOVA) REFERENCES EXECUTAVEIS(ID)',
      'ALTER TABLE LOGS_DEPLOY_VERSOES ADD CONSTRAINT FK_LOGSDEPLOYVERSOES_STATDEPL FOREIGN KEY (ID_STATUS_DEPLOY) REFERENCES TIPOS_STATUS_DEPLOY(ID)',

      //Para funcionar corretamente o gerenciador de totens e o totem AA, deve-se criar esta FK abaixo nesta tabela.
      //  Porém, esta alteração necessita que o campo ID seja PK na tabela TOTENS, ou seja depende da alteração grande no SicsServidor
      //  descrita acima. Desta forma, ficará comentado neste momento e POSTERIORMENTE DEVERÁ ser criada esta PK, junto com a versão do servidor:
      //  'ALTER TABLE LOGS_DEPLOY_VERSOES ADD CONSTRAINT FK_LOGSDEPLOYVERSOES_TOTEM FOREIGN KEY (ID_TOTEM) REFERENCES TOTENS(ID)',

      'CREATE TABLE SETORES (ID INTEGER NOT NULL, ID_UNIDADE INTEGER, NOME VARCHAR(100))',
      'ALTER TABLE SETORES ADD CONSTRAINT PK_SETORES PRIMARY KEY (ID)',
      'ALTER TABLE SETORES ADD CONSTRAINT FK_SETORES_UNIDADES FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES (ID)',
      //450

      'ALTER TABLE TOTENS ADD ID_SETOR INTEGER',
      'ALTER TABLE TOTENS ADD CONSTRAINT FK_TOTENS_SETORES FOREIGN KEY (ID_SETOR) REFERENCES SETORES (ID)',

      'CREATE TABLE PIS_ALARMES_ATIVOS_POR_PA (ID_UNIDADE INTEGER NOT NULL, ID_PA INTEGER, NOMEINDICADOR VARCHAR(60), NOMENIVEL VARCHAR(30), CODIGOCORNIVEL INTEGER, MENSAGEM VARCHAR(1000))',
      'ALTER TABLE PIS_ALARMES_ATIVOS_POR_PA ADD CONSTRAINT FK_PISALARMESATIVOSPA_UNIDADES FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID)',

      'CREATE TABLE QTD_ESPERA_POR_PA (ID_UNIDADE INTEGER NOT NULL, ID_PA INTEGER, QTD_ESPERA INTEGER)',
      'ALTER TABLE QTD_ESPERA_POR_PA ADD CONSTRAINT FK_QTDESPERAPORPA_UNIDADES FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID)',

      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL} CREATE PROCEDURE pr_is_SICS_s_Alarmes(@ID_UNID_CD_UNIDADE INT, @ID_BOUN_NR_BOX INT) AS ' +
        'SET NOCOUNT ON BEGIN SELECT UNIDADE.ID_UNID_CLI   AS idUnidade, ALARME.ID_PA AS nrBox, ALARME.NOMEINDICADOR AS indicadorPerformance, ' +
        'ALARME.NOMENIVEL AS indicadorNivelAlarme, ALARME.CODIGOCORNIVEL AS corAlarme, ALARME.MENSAGEM AS mensagemAlarme FROM PIS_ALARMES_ATIVOS_POR_PA ALARME  WITH(NOLOCK) ' +
        'INNER JOIN UNIDADES UNIDADE WITH(NOLOCK) ON ALARME.ID_UNIDADE = UNIDADE.ID WHERE UNIDADE.ID_UNID_CLI = @ID_UNID_CD_UNIDADE AND ALARME.ID_PA = @ID_BOUN_NR_BOX END;{FI};',
      '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}CREATE PROCEDURE pr_is_SICS_s_SenhasEspera(@ID_UNID_CD_UNIDADE INT, @ID_BOUN_NR_BOX	INT) AS ' +
        'SET NOCOUNT ON BEGIN SELECT UNIDADE.ID_UNID_CLI  AS idUnidade, QTDESP.ID_PA AS nrBox, QTDESP.QTD_ESPERA AS qtSenhaEspera FROM QTD_ESPERA_POR_PA QTDESP  WITH(NOLOCK) ' +
        'INNER JOIN UNIDADES UNIDADE WITH(NOLOCK) ON QTDESP.ID_UNIDADE = UNIDADE.ID WHERE UNIDADE.ID_UNID_CLI = @ID_UNID_CD_UNIDADE AND QTDESP.ID_PA = @ID_BOUN_NR_BOX END;{FI};',
      //458

      'CREATE TABLE PIS_VALORES_EM_BD (ID_UNIDADE INTEGER NOT NULL, ID INTEGER NOT NULL {IF MSSQL}IDENTITY(1,1){FI}, NOME VARCHAR(100), VALOR VARCHAR(100), ULTIMO_VALOR_EM {IF FB}TIMESTAMP{FI} {IF MSSQL}DATETIME{FI});',
      'ALTER TABLE PIS_VALORES_EM_BD ADD CONSTRAINT PK_PISVALORESEMBD PRIMARY KEY (ID_UNIDADE, ID)',
      '{IF FB} CREATE GENERATOR GEN_ID_PIS_VALORES_EM_BD {FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      '{IF FB} CREATE TRIGGER AUTOINC_PISVALORESEMBD_ID FOR PIS_VALORES_EM_BD ACTIVE BEFORE INSERT POSITION 0 AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_ID_PIS_VALORES_EM_BD,1); END {FI}' +
        '{IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI}',
      //462
     'ALTER TABLE ATENDENTES ADD CONVENIOMODULAR {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI};',
     'ALTER TABLE MODULOS_PAS ADD MOSTRAR_BOTAO_DADOS_ADICIONAIS {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
     'ALTER TABLE MODULOS_PAS ADD GRUPOS_DE_TAGS_LAYOUT_BOTAO VARCHAR(500);',
     'ALTER TABLE MODULOS_PAS ADD GRUPOS_DE_TAGS_LAYOUT_LISTA VARCHAR(500);',
     'ALTER TABLE MODULOS_PAS ADD GRUPOS_DE_TAGS_SOMENTE_LEITURA VARCHAR(500);',
     'ALTER TABLE MODULOS_MULTIPAS ADD MOSTRAR_BOTAO_DADOS_ADICIONAIS {IF FB} BOOLEAN{FI}{IF MSSQL} CHAR(1){FI};',
     'ALTER TABLE MODULOS_MULTIPAS ADD GRUPOS_DE_TAGS_LAYOUT_BOTAO VARCHAR(500);',
     'ALTER TABLE MODULOS_MULTIPAS ADD GRUPOS_DE_TAGS_LAYOUT_LISTA VARCHAR(500);',
     'ALTER TABLE MODULOS_MULTIPAS ADD GRUPOS_DE_TAGS_SOMENTE_LEITURA VARCHAR(500);',
     '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_PAS ADD DEFAULT(''F'') FOR MOSTRAR_BOTAO_DADOS_ADICIONAIS{FI};',
     '{IF FB}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco + '{FI} {IF MSSQL}ALTER TABLE MODULOS_MULTIPAS ADD DEFAULT(''F'') FOR MOSTRAR_BOTAO_DADOS_ADICIONAIS{FI};',
     'ALTER TABLE MODULOS_TGS ADD MOSTRAR_RELATORIO_TMAA {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI};',
     'ALTER TABLE MODULOS_ONLINE ADD MOSTRAR_TAGS_PREENCHIDAS {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI};',

      //475
      'CREATE TABLE MODULOS_TV (ID INTEGER NOT NULL, CHAMADAINTERROMPEVIDEO {IF FB} BOOLEAN {FI}{IF MSSQL} CHAR(1){FI},'+
      'MAXIMIZARMONITOR1 {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, MAXIMIZARMONITOR2 {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI},'+
      'FUNCIONASABADO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, FUNCIONADOMINGO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, '+
      'USECODEBAR {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, IDPAINEL INTEGER, IDTV INTEGER, PORTAIPPAINEL INTEGER,'+
      'LASTMUTE INTEGER, VOLUME INTEGER, DEM INTEGER, ATEM INTEGER, CODEBARPORT VARCHAR(20), '+
      ' INDICADORESPERMITIDOS VARCHAR(400), DEH INTEGER, ATEH INTEGER, ID_UNIDADE INTEGER);',

      'ALTER TABLE MODULOS_TV ADD CONSTRAINT PK_MODULOS_TV PRIMARY KEY (ID);',

      'CREATE TABLE MODULOS_TV_PAINEIS (ID INTEGER NOT NULL, ID_MODULO_TV INTEGER,TIPO INTEGER,'+
      'BACKGROUNDFILE VARCHAR(200),FONTE VARCHAR(50),ARQUIVOSOM VARCHAR(200),FLASHFILE VARCHAR(200),CAMINHODOEXECUTAVEL VARCHAR(200),'+
      'NOMEDAJANELA VARCHAR(50),RESOLUCAOPADRAO CHAR(50),ARQUIVOSVIDEO VARCHAR(200),HOSTBANCO VARCHAR(50),PORTABANCO VARCHAR(50),'+
      'NOMEARQUIVOBANCO VARCHAR(200),USUARIOBANCO VARCHAR(50),SENHABANCO VARCHAR(50), DIRETORIOLOCAL VARCHAR(200),'+
      'LAYOUTSENHAX INTEGER,LAYOUTSENHAY INTEGER, LAYOUTSENHALARG INTEGER, LAYOUTSENHAALT INTEGER, LAYOUTPAX INTEGER,LAYOUTPAY INTEGER,'+
      'LAYOUTPALARG INTEGER,LAYOUTPAALT INTEGER, LAYOUTNOMECLIENTEX INTEGER,LAYOUTNOMECLIENTEY INTEGER,LAYOUTNOMECLIENTELARG INTEGER,'+
      'LAYOUTNOMECLIENTEALT INTEGER,QUANTIDADE VARCHAR(50), ATRASO VARCHAR(50), ESPACAMENTO VARCHAR(50),PASPERMITIDAS CHAR(400),'+
      'MARGEMSUPERIOR INTEGER,MARGEMINFERIOR INTEGER, MARGEMESQUERDA INTEGER,MARGEMDIREITA INTEGER,FORMATO VARCHAR(50),'+
      'NOMEARQUIVOHTML VARCHAR(200),INDICADORSOMPI VARCHAR(200), ARQUIVOSOMPI VARCHAR(200), "LEFT" INTEGER, "TOP" INTEGER,'+
      'HEIGHT INTEGER, WIDTH INTEGER, COLOR INTEGER, FONTESIZE INTEGER,FONTECOLOR INTEGER, SOFTWAREHOMOLOGADO INTEGER,DISPOSITIVO INTEGER,'+
      'RESOLUCAO INTEGER, TEMPOALTERNANCIA INTEGER,IDTVPLAYLISTMANAGER INTEGER,TIPOBANCO INTEGER,INTERVALOVERIFICACAO INTEGER,'+
      'LAYOUTSENHAALINHAMENTO INTEGER, LAYOUTPAALINHAMENTO INTEGER, LAYOUTNOMECLIENTEALINHAMENTO INTEGER, SOMVOZCHAMADA0 INTEGER,'+
      'SOMVOZCHAMADA1 INTEGER, SOMVOZCHAMADA2 INTEGER, VOICEINDEX INTEGER, ATUALIZACAOPLAYLIST DATE, '+
      'TRANSPARENT {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI},NEGRITO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI},'+
      'ITALICO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, SUBLINHADO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, '+
      'MOSTRARSENHA {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, MOSTRARPA {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, '+
      'MOSTRARNOMECLIENTE {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, SOMARQUIVO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI},'+
      'SOMVOZ {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, SOMVOZCHAMADA1MARCADO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI},'+
      'SOMVOZCHAMADA2MARCADO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, SOMVOZCHAMADA3MARCADO {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI},'+
      'DISPOSICAOLINHAS {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, VALORACOMPANHACORDONIVEL {IF FB} BOOLEAN {FI}{IF MSSQL}CHAR(1){FI}, ID_UNIDADE INTEGER);',

      'ALTER TABLE MODULOS_TV_PAINEIS ADD CONSTRAINT PK_MODULOS_TV_PAINEIS PRIMARY KEY (ID);',

      'ALTER TABLE MODULOS_TV_PAINEIS ADD CONSTRAINT FK_MODULOS_TV_PAINEIS_1 FOREIGN KEY (ID_MODULO_TV) REFERENCES MODULOS_TV (ID);',

      '{IF FB}CREATE GENERATOR GEN_MODULOS_TV_PAINEIS_ID {FI} {IF MSSQL} ' + UpdatePadraoParaNaoFicarInstrucaoEmBranco +'{FI}',

      '{IF FB}SET GENERATOR GEN_MODULOS_TV_PAINEIS_ID TO 1 {FI} {IF MSSQL}' + UpdatePadraoParaNaoFicarInstrucaoEmBranco +'{FI}',

      'ALTER TABLE MODULOS_PAS ADD PERMITEFINALIZAR {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI};',
      'ALTER TABLE MODULOS_MULTIPAS ADD PERMITEFINALIZAR {IF FB}BOOLEAN{FI} {IF MSSQL}CHAR(1){FI};');

implementation


end.

